#include <iostream>
#include <Windows.h>

using namespace std;

void TextColor(int font, int backGround);

void main()
{
	//Example_02
	// 좋아하는 캐릭터 출력 2
	TextColor(0, 0);
	cout << "                   ";
	TextColor(15, 15);
	cout << "          ";
	TextColor(0, 0);
	cout << "                     \n";
	TextColor(0, 0);
	cout << "             ";
	TextColor(15, 15);
	cout << "                      ";
	TextColor(0, 0);
	cout << "              \n";
	TextColor(0, 0);
	cout << "         ";
	TextColor(15, 15);
	cout << "                              ";
	TextColor(0, 0);
	cout << "          \n";
	TextColor(0, 0);
	cout << "     ";
	TextColor(15, 15);
	cout << "                                    ";
	TextColor(0, 0);
	cout << "        \n";
	TextColor(0, 0);
	cout << "     ";
	TextColor(15, 15);
	cout << "                                      ";
	TextColor(0, 0);
	cout << "      \n";
	TextColor(0, 0);
	cout << "   ";
	TextColor(15, 15);
	cout << "                                          ";
	TextColor(0, 0);
	cout << "     \n";
	TextColor(0, 0);
	cout << " ";
	TextColor(15, 15);
	cout << "                                              ";
	TextColor(0, 0);
	cout << "   \n";
	TextColor(0, 0);
	cout << " ";
	TextColor(15, 15);
	cout << "                                              ";
	TextColor(0, 0);
	cout << "   \n";
	TextColor(15, 15);
	cout << "                                                 \n";
	TextColor(15, 15);
	cout << "                                                 \n";
	TextColor(15, 15);
	cout << "                                                 \n";
	TextColor(15, 15);
	cout << "        ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "                  ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "               \n";
	TextColor(15, 15);
	cout << "        ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "                  ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "               \n";
	TextColor(15, 15);
	cout << "                                                 \n";
	TextColor(8, 8);
	cout << "                                       ";
	TextColor(15, 15);
	cout << "           \n";
	TextColor(8, 8);
	cout << "                                  ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(8, 8);
	cout << "  ";
	TextColor(15, 15);
	cout << "          \n";
	TextColor(8, 8);
	cout << "                                ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "          \n";
	TextColor(8, 8);
	cout << "                              ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "      ";
	TextColor(15, 15);
	cout << "      \n";
	TextColor(8, 8);
	cout << "                            ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                    \n";
	TextColor(8, 8);
	cout << "                          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                      \n";
	TextColor(15, 15);
	cout << "                          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                     \n";
	TextColor(15, 15);
	cout << "                          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                     \n";
	TextColor(15, 15);
	cout << "                          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                     \n";
	TextColor(15, 15);
	cout << "                            ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                   \n";
	TextColor(5, 15);
	cout << "                              ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                 \n";
	TextColor(15, 15);
	cout << "                                ";
	TextColor(0, 0);
	cout << "      ";
	TextColor(15, 15);
	cout << "           \n";

}


void TextColor(int font, int backGround) {
	int color = font + backGround * 16;
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), color);
}