#include <iostream>
#include <Windows.h>

using namespace std;

using std::cout;
using std::endl;

void TextColor(int font, int backGround);

void main() {
	TextColor(15, 15);
	cout << "                                                      \n";
	TextColor(15, 15);
	cout << "            ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "                      ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "            \n";
	TextColor(15, 15);
	cout << "          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "          \n";
	TextColor(15, 15);
	cout << "          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "          \n";
	TextColor(15, 15);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "        \n";
	TextColor(15, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "        ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "              ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(3, 3);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "      \n";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "  ";
	TextColor(0, 0);
	cout << "              ";
	TextColor(9, 9);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    \n";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "                  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    \n";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(3, 3);
	cout << "          ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(9, 9);
	cout << "          ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(3, 3);
	cout << "          ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "    \n";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "    ";
	TextColor(0, 0);
	cout << "      ";
	TextColor(1, 1);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  \n";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "              ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  \n";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(9, 9);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "              ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "      ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "  \n";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "  ";
	TextColor(0, 0);
	cout << "          ";
	TextColor(9, 9);
	cout << "    ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(1, 1);
	cout << "      ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(9, 9);
	cout << "    ";
	TextColor(0, 0);
	cout << "          ";
	TextColor(3, 3);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  \n";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "          ";
	TextColor(0, 0);
	cout << "      ";
	TextColor(9, 9);
	cout << "          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(3, 3);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  \n";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "        ";
	TextColor(1, 1);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "                          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "  ";
	TextColor(0, 0);
	cout << "        ";
	TextColor(15, 15);
	cout << "  \n";
	TextColor(15, 15);
	cout << "    ";
	/*TextColor(0, 0);
	cout << "  ";*/
	TextColor(1, 1);
	cout << "        ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(9, 9);
	cout << "                      ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(1, 1);
	cout << "        ";
	/*TextColor(0, 0);
	cout << "        ";*/
	TextColor(15, 15);
	cout << "    \n";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "        ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(9, 9);
	cout << "                      ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(1, 1);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  \n";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "        ";
	TextColor(0, 0);
	cout << "        ";
	TextColor(9, 9);
	cout << "              ";
	TextColor(0, 0);
	cout << "        ";
	TextColor(1, 1);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  \n";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "  ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(9, 9);
	cout << "      ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(1, 1);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  \n";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "        ";
	TextColor(1, 1);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "      ";
	TextColor(0, 0);
	cout << "      ";
	TextColor(1, 1);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "  ";
	TextColor(0, 0);
	cout << "        ";
	TextColor(15, 15);
	cout << "  \n";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "                  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    \n";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "                  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(9, 9);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    \n";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "        ";
	TextColor(15, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(1, 1);
	cout << "          ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(15, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << "        ";
	TextColor(15, 15);
	cout << "    \n";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "          ";
	TextColor(0, 0);
	cout << "          ";
	TextColor(0, 0);
	cout << "";
	TextColor(15, 15);
	cout << "          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    \n";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "                              ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(1, 1);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(15, 15);
	cout << "    \n";
	TextColor(15, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "      ";
	TextColor(15, 15);
	cout << "                                  ";
	TextColor(0, 0);
	cout << "      ";
	TextColor(15, 15);
	cout << "    \n";
	TextColor(15, 15);
	cout << "                                                      ";
	TextColor(0, 0);
	cout << "\n\n\n";
}

void TextColor(int font, int backGround) {
	int color = font + backGround * 16;
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), color);
}